<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NTB-257" failures="1" tests="7" name="Wrong Credentials Login Test" time="40.595" errors="0" timestamp="2023-03-22T14:18:51 CET">
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="1.324"/>
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="1.124"/>
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="1.091"/>
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="1.067"/>
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="1.203">
    <skipped/>
  </testcase> <!-- loginWrongCredentials -->
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="1.229">
    <failure type="java.lang.AssertionError" message="expected [No customer account found!!!] but found [No customer account found]">
      <![CDATA[java.lang.AssertionError: expected [No customer account found!!!] but found [No customer account found]
at Academy.Tricentis.LoginNegative04.loginWrongCredentials(LoginNegative04.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- loginWrongCredentials -->
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="1.264"/>
</testsuite> <!-- Wrong Credentials Login Test -->
