<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NTB-257" failures="1" tests="7" name="Academy.Tricentis.LoginNegative04" time="38.525" errors="0" timestamp="2023-03-22T14:18:51 CET" skipped="1">
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="4.705"/>
  <system-out/>
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="4.545"/>
  <system-out/>
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="5.354"/>
  <system-out/>
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="4.945"/>
  <system-out/>
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="7.990"/>
  <system-out/>
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="6.354">
    <failure message="expected [No customer account found!!!] but found [No customer account found]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [No customer account found!!!] but found [No customer account found]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Academy.Tricentis.LoginNegative04.loginWrongCredentials(LoginNegative04.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- loginWrongCredentials -->
  <system-out/>
  <testcase classname="Academy.Tricentis.LoginNegative04" name="loginWrongCredentials" time="4.632">
    <skipped/>
  </testcase> <!-- loginWrongCredentials -->
  <system-out/>
</testsuite> <!-- Academy.Tricentis.LoginNegative04 -->
